title: FAN Jue
email: jue.fan@u.nus.edu
description: PhD Student @ NUS
baseurl: "" 
url: "https://github.com/FYimu"

# Build settings
#theme: minima # Or leave blank if using custom CSS
plugins:
  - jekyll-feed

collections:
  updates:
    output: false
  courses:
    output: false
  education:
    output: false
  teaching:
    output: false
  publications:
    output: false
