title: FAN Jue
email: jue.fan@u.nus.edu
description: PhD Student @ NUS
baseurl: "" 
url: "https://github.com/FYimu"

# Build settings
#theme: minima # Or leave blank if using custom CSS
plugins:
  - jekyll-feed